# import math
ttlAmt = float(input("Total: "))
tipPerc = int(input("Tip %: ")) / 100
splitAmt = int(input("Amount of people: "))
print("Each person pays " + str((ttlAmt + (tipPerc * ttlAmt)) / splitAmt))


#      """""     uOOOOOOOOOOOOOY0OOOOOOOddddd****%%%%%%%%qmmOOOOOOOOOOOOOOOOOOOOd%%%%%#ddwd****%%%%%%%**a***%***dd**d*k%***%%%%%&%%****|^*||^^^^^^^^^^^^^^^^^^^^************ddddOOOOYYYYuuuuuuuuuuuuuuu|""     """""   
#      """""     uOOOOOOZOYYYYYYYYYOOOOOOdddd****%%%%%%%%OOOOOOOOOOOOOOOOOOOOOd*%%%%%*d*dOOd*******%**%***********dd***d%%&a*#%**%%%*******d^c^^^^^^^^^^^^^^^^^^************ddddOOOOYYYYYuuuuuuuuuuuuuu|""     """""   
#      """""     uOOYYYYYYYYYYYYYYYYYOOOOOdddd****%%%%%%%OOOOOOOOOOOOOOOOOOOOa%%%%%#****kdd***%%%%*o*****&******d*dOd*****%*%8**%%%%%%&*******!O^^^^^^^^^^^^^^^^************dddddOOOOYYYYuuuuuuuuuuuuuu|""     """""   
# """""     """""tYYYYYYYYYYYYYYYYYYYYOOOOOddd****%%%%%%%OOOOOOOOOOOOOOOOOOO*%%%%%%%%%*d********dddO*h****%%W%%%%*d*Odd**&O*%%%%%%%%%%%%*****d*d#^^^^^^^^^^^^^^^************dddddOOOOYYYYYuuuuuuuuuuuuu(  """""     """
# """""     """""tYYYYYYYYYYYYYYYYYYYYYOOOOpddd****%%%%%%OOOOOOOOOOOOOOOOOOh%%%%%%%%8&%****W%%%%%********dk***%%%%%wb%*%%%%%h*%%%*%%%%%%%%*******dY^^^^^^^^^^^||************kddddOOOOYYYYYuuuuuuuuuuuuu(  """""     """
#      """""     fYYYYYYYYYYYYuuuuuYYYYYOOOOdddd***%%%%%%OOOOOOOOOOOOOOOOOm%%%%%%%%%%&***%%%%%****%%*d*d*******da*h%#%**d%%#%%%*%%W%%%%%%%%*******hu|^^^^|||||||*************ddddOOOOOYYYYYuuuuuuuuuuuuf""     """""   
#      """""     fYYYYYYYYYXuuuuuuuuuYYYYOOOOddd****%%%%%OOOOOOOOOOOOOOOOO%%%%%%%%%%%%%%%%%%%M**M%%%%*******oa%W***%k#a%*dOQdQd**%M%%%%%**%%*******dC|||||||||||*************dddddOOOOYYYYYYcuYYYYYYYYYf""     """""   
#      """""     fYYYYYYYuuuuuuuuuuuuuYYYYOOOddd****%%%%%OOOOOOOOOOOOOOOq%%%%%%%%%%%%%%%%%%%%%%%%%#*****%M***********%8ad*%%***dk**%%%%%%d***ddd****d|||||||||||*************oddddOOOOYYYYYYYYYYYYYYYYYf""     """""   
# """""     """""tYYYYYuuuuuuuuuuuuuuuvYYYOOOdddb***%%%%%OOOOOOOOOOOOOOO%%%%%%%%%%%%%%%%%%&*%%%%**%***%**%*****%%%%%%***%&*M*%**0*%*%%%%*dd**dddd*%**\||||||||||**************ddddOOOOOYYYYYYYYYYYYYYYYt  """""     """
# """""     """""tYYYuuuuuuuuuuuuuuuuuuYYYOOOpddb***%%%%%OOOOOOOOOOOOOOd%%%%%%%%%%%%%%%%%%%%%%%%***h********%%#*********dd******%d*%%%**W%d***ddd*M%%u|||||||\uu******%%******dddddOOOOOYYYYYYYYYYYYYYYt  """""     """
#      """""     fYYuuuuuuuuuuuuuuuuuuuYYYOOOddd****%%%%%OOOOOOOOOOOOOO*%%%%%%%%%%%%%%%%%%%%%%%***%%%***%%*b*d******adOdOCOd*******M*****8*dd**dd**%%u/|||uuuuuu******%%%******ddddZOOOOQYYYYYYYYYYYYYYf""     """""   
#      """""     fYuuuuuuuuuuuuuuuuuuuuYYYOOOddd***%%%%%%OOOOOOOOOOOO0Q%%%%%%%%%%%%%%%%%%%%%%%%%*%*%%%%%%*******WdOCCnnnnnCJCddddd******d**ddd****%8&uuuuuuuuuuu******%%%%*****dddddOOOOOJYYYYYYYYYYYYYf""     """""   
#      """""     fuuuuuuuuuuuuuuuuuuuuzYYYOOOddd***%%%%%%OOOOOYYYYYYYYO%%%%%%%%%%%%%%%%%%%%%%%%%****%%%*&****dCCnnn|||||nnnnnnCOOd******dd**d***%**%Ouuuuuuuuuuu******%%%%%*****dddddOOOOOOYYYYYYYYYYYYf""     """""   
# """""     """""tuuuuuuuuuuuuuuuuuuuuYYYYOOOddd***%%%%%%OOYYYYYYYuuuuuO%%%%%%%%%%%%%%%%%%%%%%%*****&****ddCunnnn|||||||||nnnnCCOdOCOddd********%%%*uuuuuuuuuuuYd*****%%%%%******ddddZOOOOOOYYYYYYYYYYYt  """""     """
# """""     """""tuuuuuuuuuuuuuuuuuuuuYYYOOOddd***%%%%%%%YYYYYYuuuuuuu||%%%%%%%%%%%%%%%%%%***%%oo*%%CunnnCn|||||t|||||||||||nnnnCCCuCCOd****d%*%%%%buuuuuuuYYYYYd******%%%%8*****dddddOOOOOOOOYYYYYYOOOn  """""     """
#      """""     fuuuuuuuuuuuuuuuuuuuuYYYOOOddd***%%%%%%%YYYYuuuuuu||||Y*%**#%%%%%%%%%%%***W*OOOCUnn/||||nn|||||||||||||||||||nnnnnnnCCod*%%*%%%%%%%YuuuYYYYYYYYdd*****M%%%%*****dddddOOOOOOOOOOOOOOOOOu""     """""   
#      """""     fuuuuuuuuuuuuuuuuuuuYYYYOOOddd***%%%%%%%YYzuuuu|||||||u*%%%%%%%%%%%%%%#*dOCCCCCCnn|||/||nn||||||||||||||||||||nnnnnnJCda*%%%%%%%%%*YYYYYYYYYYYYddd*****%%%******ddddddOOOOOOOOOOOOOOOOu""     """""   
#      """""     fuuuuuuuuuuuuuuuuuuuYYYYOOOddd***%%%%%%%YYYuuuur||||||UM**%%%%%%%%%**%*dddQnnnnnnnnnxn||nnn|||||||||||||nnnnCCCnnnnnCCd***%%%%%%%%%OYYYYYYYYYYYddd**************ddddddOOOOOOOOOOOOOOOOu""     """""   
# """""     """""tuuuuuuuuuuuuuuuuuuuYYYYOOOddd***%%%%%%%YYYuuuuu||||||%%%%%%%%%%%%%**%%%%*****q0Cnnnnnnnnnn||n|||nnnnndad*addd*dQCCnCCdd*%%%%%%%%%%dYYYYYYYYYYOdddd*************dddddddOOOOOOOOOOOOOOOn  """""     """
# """""     """""tuuuuuuuuuuuuuuuuuuuuYYYOOOOddd***%%%%%%YYuuuuuu|||||u%%%%%%%%%%%8**%%%%%%%%%%******addCn0n|nCO0C******%**ddOOCCCCCCcndmd*%%%%%%%%%*YYYYYY0OOOOZddd************dddddddOOOOOOOOOOOOOOOOn  """""     """
#      """""     fuuuuuuuuuuuuuuuuuuuuYYYYOOOddd****%%%%%YYuuuuuu/||||O%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%*ddmCXCLCOO**%%%%**dwQCChCnCCnnnnOd*%%%%%%%%%%dOYYOOOOOOOOdddd***********dddddddOOOOOOOOOOOOOOOOu""     """""   
#      """""     fuuuuuuuuuuuuuuuuuuuuvYYYOOOOddd***%%%%%YYuuuuuuu||||Y%%%%%%%%%%%*********W%%%%W%%%%%%%%%On|||nO***%%*M%%*%*d*dCYn|nnnnnLO**%%%%%%%**OOOOOOOOOOOdddddd*******ddddddddOOOOOOOOOOOOOOOOOu""     """""   
#      """""     fYuuuuuuuuuuuuuuuuuuuuYYYYOOOOddd****%%%YYXuuuuuuj||uuO%%%%%%%%%%***dhd**%**dh*OdwhwOd*%dCnn|||/CCCCCCCCCCCCCCCnnnnnnnnnCC**%%%%%%*dOOOOOOOOOOOOOdddddddddddddddddddOOOOOOOOOOOOOOOOOOu""     """""   
# """""     """""tYuuuuuuuuuuuuuuuuuuuuuYYYYOOOOddd****%%YYuuuuuuuu|||uu*%%%%%%%%%***dddd****ddOCCCOCOOdddOn|||||||nnnnCmdO0CCun|/n|nnnnnC0**%%%%&ddOOOOOOOOOOOOCOOmddddddddddddddddOOOOOOOOOOOOOOOOOOOn  """""     """
# """""     """""tYYuuuuuuuuuuuuuuuuuuuuuYYYYOOOOddd*****YYYuuuuuuuu||||O&%%%%%%%%%**ddddOddOdqCCCCCCCCnd*dn||||||||||||||||||||||||nnnnCCO**%%%*COOOOOOOOOOOOOOCQOOOdddddddddddddOOOOOOOOOOOOOOOOOOOOOn  """""     """
#      """""     fYuuuuuuuuuuuuuuuuuuuuuuuYYYYOOOOdddd***YYYuuuuuuuuu/|||Yk%%%%%%%%%**dOOCCCCCCCCUnnnCCCO*Cnr|||||nn||||||||||||||nnnnnnCCq**%*OCOOOOOOOOOOOOOOOCCCOOOOOOddddddOOOOOOOOOOOOOOOOOOOOOOOOu""     """""   
#      """""     fYYuuuuuuuuuuuuuuuuuuuuuuuYYYYYOOOdddd**YYYYuuuuuuuuuu||||u%%%%%%%%%*ddOCCCCnnnnnnnnCdd*OCnn||||nnznnn||||||||||nnnnnnCCCOd*dCCnOOOOOOOOOOOOmmdCCCCCOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOu""     """""   
#      """""     fYYYuuuuuuuuuuuuuuuuuuuuuuucYYYJOOOdddd*YYYuuuuuuuuuuuu||||f%%%%%%%%**ddOCCCnnnnnnnnCddoCCn|||||n||JdCnnn|||nnnnnnnnnnCCCOOCnCnCOOOOOOOOZddddddCCCCCCCOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOu""     """""   
# """""     """""tYYYuuuuuuuuuuuuuuuuuuuuuuuuuYYYYOOOpdddYYYYuuuuuuuuuuuu||||Y%%%%%%%%**ddOCCCCnnnnCOLdd**dCnnnnCCnnnnndCCnnnnnnnnnnnnnCCCCnn|||COOOOOOmZdddddddCCCCCCCCCCOOOOOOOOOOOOOOOOOOOOOOOOOOOOOc  """""     """
# """""     """""tYYYYuuuuuuuuuuuuuuuuuuuuuuuuuYYYYOOOdddYYYYuuuuuuuuuuuuu||||d%%%%%%%8***dwCCCCCCCCCO%%%%%*dddp&*dOn||ndCCnnnnnnnnnnnnCCCnnnn||COOOOOqdddddddddCCCCCCCCCCCCCOOOOOOOOOOOOOOOOOOOOddddddc  """""     """
#      """""     fYYYYuuuuuuuuuuuuuuuuuuuuuuuuuuYYYYOOOddYYYYzuuuuuuuuuuuuuuuum%%%%%%%%**ddwOCCCCCCCCd**%%%%**dOCCnn||||ndOCnnnnnnnnnnCCCOdCnnnnwdddddddddddddddCCCCCCCCCCCCCCOOOOOOOOOOOOOOOddddddddddX""     """""   
#      """""     fYYYYYuuuuuuuuuuuuuuuuuuuuuuuuuvYYYOOOOdYYYYYuuuuuuuuuuuuuuuum%%%%%%%%**dddOCCCCCOCCCCddddZ\CCn|||||||||nCCCnnnnnnnnnCCCddpddddddddddddddddddddCCCCCCCCCCCCCOOOOOOOOOOOOOOddddddddddddX""     """""   
#      """""     fYYYYYYuuuuuuuuuuuuuuuuuuuuuuuuuYYYYOOOOYYYYYuuuuuuuuuuuuuuuuuud%%dO%%**ddOCCCCCOCCCCCCOOCCCCCCCCCCnnn||||CCnnnnnnnncCC0dddddddddddddddddddddddCCCCCCCCCCCCOOOOOOOOOOdddddddddddddddddX""     """""   
# """""     """""tYYYYYYYuuuuuuuuuuuuuuuuuuuuuuuuuYYYYOOOYYYYYuuuuuuuuuuuuuuuuuuYYJOOd%%*d*OCCnnCmdd**%%****d*dO|*md%**mCn\jCnnnnnnnnCCCddddddddddddddddddddddddCCCCCCCCCOOOOOOOOOOOOddddddddddddddddddc  """""     """
# """""     """""tYYYYYYYuuuuuuuuuuuuuuuuuuuuuuuuuYYYYCOOYYYYYXuuuuuuuuuuuuuuuuYYYOOOd*%***OCnnnO**dd*W*dCOnntzn|uuv%**ddCnnnnnnnnnnUCCOddddddddddddddddddddddddCCCCCCC0OOOOOOOOOOOOdddddddddddddddddddc  """""     """
#      """""     fYYYYYYYYuuuuuuuuuuuuuuuuuuuuuuuuuYYYYOOYYYYYYYuuuuuuuuuuuuuuuYYYOOOdd%%**oCnnnO**aLOd%d*k*mOQCdCCCCCnnCCCnnnnnnnnCCCCOddddddddddddddddddddddddCCCCCOOOOOOOOOOOOOdddddddddddddddddddddX""     """""   
#      """""     fYYYYYYYYuuuuuuuuuuuuuuuuuuuuuuuuuYYYYYOYYYYYYzuuuuuuuuuuuuuuuYYYOOOddd%%%*dCnnOddQCCLdddmCCCCCCCnnnnnCnCnnnnnnnCCCCOCOddddddddddddddddddddddddCOOOOOOOOOOOOOOOqddddddddddddddddddddddX""     """""   
#      """""     fYYYYYYYYYuuuuuuuuuuuuuuuuuuuuuuuuuYYYYYYYYYYYYuvuuuuuuuuuuuuYYYOOOddddd%%%*pnnC***dCCCCCCzCCXXUXCCQdhCCnnnnnCCOOOCCCCOddddddddddddddddddddddddOOOOOOOOOOOOOZdddddddddddddddddddddddddX""     """""   
# """""     """""tYYYYYYYYYuuuuuuuuuuuuuuuuuuuuuuuuuYYYYYYYYYYYYYuuuuuuuuuuuuuYYYOOOddddd*%%%%*COb*%%**dddh***WW%%*hqCCnnnnnnCOOCCOOOCCOddddddddddddddddddddddddOOOOOOOqdddddddddddddddddddddddddddddddc  """""     """
# """""     """""tYYYYYYYYYYuuuuuuuuuuuuuuuuuuuuuuuuuYYYYYYYYYYYYYuuuuuuuuuuuuYYYOOOdddddh%%%%%%*******%M%*ddOCCCCnnnnnnnnXCCOCCCOdOCnUOddddddddddddddddddddddddOOOOdddddddddddddddddddddddddddddddddddc  """""     """
#      """""     fYYYYYYYYYYuuuuuuuuuuuuuuuuuuuuuuuuuuYYYYYYYYYYYYuuuuuuuuuuuuYYYOOOdddddd%%%%%%%*ddddOCCddOOCCnnnnncznnnnCCCCCOddOCnnnOddddddddddddddddddddddddOOOddddddddddddddddddddddddddddddddddddX""     """""   
#      """""     fYYYYYYYYYYYuuuuuuuuuuuuuuuuuuuuuuuuuYYYYYYYYYYYYYzuuuuuuuuuYYYYOOqdddddd%%%%%%%%%*dOOQOdddOO0CCCCnrnnnnCCCCCOddOCCnnnOddddddddddddddddddddddddOOOddddddddddddddddddddddddddddddddddddX""     """""   
#      """""     fYYYYYYYYYYYuuuuuuuuuuuuuuuuuuuuuuuuuuYYYYYYY%%YYYcYuuuuuuuuYYYYOOddddddd*%%%%%%%%%%*dpOddddddOOOOCCCCCOOOCOddOCCCCnnnCddddddddddddddddd%%dddddOOdddddddddddddddddddddddddddddddddddddX""     """""   
# """""     """""tYYYYYYYYYYYYuuuuuuuuuuuuuuuuuuuuuuuuYYYYYYYO^%YYYYYYYYYvuuuYYYYOOddddddd*%%%%%%%%%%%%*ddddd**dddddddddOOOOdOCCCCnnnnnnqdddddddddddddddd^^dddddOOdddddddddddddddddddddddddddddddddddddc  """""     """
# """""     """""tYYYYYYYYYYYYuuuuuuuuuuuuuuuuuuuuuuuuYYYYYYYO^%YYYYY%^^^^^Y%^^^^^k^^^%ddd*%%^^^^k%%%%%%^^^^%d^^dd%^%&^^^^%^^^^^%n%^^^^%Yd{^^^^%d^0^^^^dd^^dddddOddddddddddddddddddddddddddddddddddddddc  """""     """
#     ."""""     fYYYYYYYYYYYYYuuuuuuuuuuuuuuuuuuuuuuYYYYYYYYO^%YYYYY%%YY%^%%^%YO^%dd^lddd*%%%%%%^%%%%%^^%W%dd^^Zd%^%&^%dd^kCCC^%%^%nn%^%^^ddd%^d^^dd%^%d%^dddddZddddddddddddddddddddddddddddddddddddddX""     """""   
#      """""     fYYYYYYYYYYYYYvuuuuuuuuuuuuuuuuuuuuuYYYYYYYYO^%YYYYY^^%%%^%%^%OO^%dd^lddd*%^^%%%^%%%%%%%%0^^*^^**%^%%^%d0^%Cnn^%%^%%%%%%^^ddd%^W^^dd%^%d%IdddddZddddddddddddddddddddddddddddddddddddddX""     """""   
#      """""     fYYYYYYYYYYYYYYXuuuuuuuuuuuuuuuuuuuuYYYYYYYYO^%YYYYM^"%%^^%%^%OO^%dd^lddd*%^%%%^^%%%%%^^%%^^*%^%%^^%&^%CC%^,%^^%n;^%%^^w%^^%%^%d^^dd%^%d^^ddd*dZddddddddddddddddddddddddddddddddddddddX""     """""   
# """""     """""tYYYYYYYYYYYYYYYuuuuuuuuuuuuuuuuuuuYYYYYOOYYYYYYYYYYYYJYYYYYYUOOOddd*o**d********8%%%%%%%%****dbZCCCCCCCCf%nn8^%nnnncnnnnn|Jdddddddddoddo******Oddddddddddddddddddddddddddddddddddddddc  """""     """
# """""     """""tYYYYYYYYYYYYYYYYuuuuuuuuuuuuuuuuuuYYYYYOOOOOYOYYYYYYYYYYYYYYOOOdddd****h*******************ddddOOCCCCCCC#^^^^%nnnnnnnnnnnnn||Odok*d***********Oddddddddddddddddddddddddddddddddddddddc  """""     """
#      """""     fYYYYYYYYYYYYYYYYYuuuuuuuuuuuuuuuuYYYYYYOOOOOOOOOYYYYYYYYYYYOOOOddd**************ddddd***ddddOddddOCCCCCCCCnCCCCCnnnnnnnnnnnn||||jO8***********OddddddddddddddddddddddddddddddddddddddX""     """""   

